spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: moviebookingdb

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: movie-booking-group
    template:
      default-topic: ticket-booking-status-topic

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
